README.md
package.json
src/intersection.js
yarn.lock

Remove polyfill

---

index.d.ts

Allow null for root and array values for threshold in TS definitions

Update TypeScript definitions

---

package.json

chore(package): update flow-bin to version 0.67.1

---

index.d.ts

Greetings!
I have been using this for a while using Typescript; I saw #41 was open, and thought that I can give back and address it :)
Tl;dr, the types:
- From actual use, are correct with respect to being valid Typescript (they check correctly etc.) :tada:.
- Reading through, they also seem correct.
- Are consistent with the Flow types & the source code
Thus, the changes in this PR are not required in any way, but they do make things a bit more consistent.

Check up TS types

---

README.md
index.d.ts
src/index.js
src/intersection.js
stories/Observer.story.js
tests/Observer.test.js
tests/__snapshots__/Observer.test.js.snap
tests/intersection.test.js

Adds back support for plain children for #90 - adds new examples and docs

Keep plain children support

---

src/__tests__/intersection.test.js
src/index.js
src/intersection.js
stories/Hooks.story.js
stories/Observer.story.js

fix: broken default threshold (#141)

---

README.md

Add note about constant threshold array

---

src/InView.tsx
src/__tests__/Observer.test.js
yarn.lock

fix: don't add onChange prop to the plain children container

---

README.md

Removed a few unnecessary commas and fixed a few other small errors.

Fixed grammatical errors in README

---

src/InView.tsx

This changes the rendering flow in the `<InView>` component, optimizing it for the children.
Previously it had a an internal `state` used to store the current `inView` and `entry` values. But it was only really used by the component when using the render props pattern. This lead to unnecessary renders for the plain component.
Another optimization tried to limit the state updates, so it would only occur if `inView` changed. This however meant you wouldn't get the correct `entry` value in the render prop, since it would only update when `inView` changes. This would prevent you from getting the latest `threshold` or `isVisible` values.

fix: optimize InView

---

src/stories/intro.story.mdx

Fixes a small typo in intro.story.mdx

Fix typo in intro.story.mdx

---

README.md
package.json
src/InView.tsx
src/__tests__/observe.test.ts
src/index.tsx
src/observe.ts
src/observers.ts
src/useInView.tsx
yarn.lock

Expose the internal `observe` method, to enable advanced workflows.

feat: export the observe method

---

src/observe.ts
src/test-utils.ts

fix: clear observers after each test run

---

src/stories/Hooks.story.tsx
src/stories/InView.story.tsx

docs: fix storybook multiple thresholds

---

src/index.tsx
src/observe.ts
src/test-utils.ts

fix: correct import path for observermap

---

README.md

Took me like 5 minutes to parse issues and find the clear instructions from one your comments, so I thought this would be helpful!

Update README.md to include instructions for using test utils globally

---

README.md

Fixed Documentation for FAQ #527

fixed #527

---

package.json
scripts/build-copy.js

Reverts thebuilder/react-intersection-observer#554

Revert "fix: correct microbundle output paths"

---

package.json
scripts/build-copy.js

This should follow the suggested format from Microbundle.
Need to validate this is working in Webpack, Next.js, Vite etc.

feat: refactor to use modern exports

---

package.json
scripts/build-copy.js

Rewrite fields in `package.json`, so they correctly map the output from Microbundle.

Update package exports

---

package.json

fix: export the test utils

---

package.json
scripts/build-copy.js

fix: export packages with dot path

---

package.json
tsup.config.ts

fix: output legacy esm

---

package.json
pnpm-lock.yaml
scripts/build-copy.cjs

- Add engines field to package.json
- Lock pnpm to version 9.0.6 with corepack

ci: upgrade pnpm to version 9

---

src/test-utils.ts

fix: test-utils - execute mockClear method only when it exists

---

.github/workflows/pkg-pr.yml
package.json
pnpm-lock.yaml
storybook/package.json

Upgrade all project dev dependencies

chore: upgrade dependencies
