- index.d.ts
The children can also be any ReactNode in React 16, as opposed to only JSX.Element. Even in React 15, the current definitions exclude `string` and `number`.
Don't import `React` with ES imports because it's not an ES module. Use a commonjs import to avoid future issues when TypeScript finally fixes their stuff.
`children` is optional, especially when `render` is provided.
The `onChange` is passed through to the top level element so if the `tag` happens to be one with an `onChange` event, the `onChange` callback may be called with `React.FormEvent`.
> Make children optional, correctness changes

- index.d.ts
Building with typescript 2.6.1 with this module included gave the error, 
```
node_modules/react-intersection-observer/index.d.ts(54,4): error TS1036: Statements are not allowed in ambient contexts.
54   };
```
It's an easy fix of simply removing the `;`.
> fixed typescript error

- README.md
The render prop example shows the function being passed to `render` returning another function, where it should just return some JSX like in the "child as function" example above it.
(P.S. shouldn't that be "function as child"?)
> Fix render prop example

- index.d.ts
Fixes incorrect module augmentation declaration, fixes exporting an undefined name.
The bulk of the change is just a reindent so looking at https://github.com/thebuilder/react-intersection-observer/pull/72/files?w=1 will be easier.
> Fix invalid index.d.ts

- package.json
It looks like it's not being packaged for npm.
(I'm not sure this is the correct fix, but it looks like it).
> Add index.d.ts to package.json files

- README.md
- package.json
- src/__tests__/hooks.test.js
- src/hooks.tsx
- src/index.tsx
- stories/Hooks.story.tsx
- stories/Observer.story.tsx
- stories/ScrollWrapper/index.tsx
- yarn.lock
This changes the hooks API to: 
```js
const [ref, inView, entry] = useInView(options)
```
See #169 for details.
> feat(hooks): changes hooks to handle the ref internally

- src/intersection.ts
- src/useInView.tsx
Using for...of created a lot of babel bloat, while requiring Symbol.iterator to be defined.
> refactor: change the Map loop to forEach

- package.json
- src/typings/types.ts
- tsconfig.build.json
- tsconfig.json
Work on improving the types for `PlainChildren` - See #202 
Create a new tsconfig for the build task. This ensures `tsc` is run on all files in the project,
while we still only emit the files in 'src'
> fix: typescript definition for PlainChildren

- docs/Recipes.md
const supportsNativeLoading is not existing, I replaced it with proper one - supportsLazyLoading
> Changed typo const supportsNativeLoading to supportsLazyLoading

- docs/Recipes.md
Fixes #270 
The first argument to the `useInView` function should be a configuration object, not a ref.
This fixes the recipe for me
> Fix recipe for triggering animations

- src/test-utils.ts
This allows mocks when the observer uses the bounding rectangle for its logic.
I wasn't sure if I should add test coverage somewhere, given these are test helpers and I didn't see precedent... let me know, and I can adjust / add to this PR!
(The husky hook also did some whitespace and formatting changes to the README.md.)
> feat: Allow specifying boundingClientRect

- src/test-utils.ts
The second argument to Intersection Observer callback is the instance of the current observer https://developer.mozilla.org/en-US/docs/Web/API/IntersectionObserver/IntersectionObserver. 
I am using this library to mock out an intersection observer implementation and is currently failing because I use the instance returned within the callback
> expose instance to the callback

- docs/Recipes.md
The latest version of the useNativeLatyLoading() Hook returns either
'false' or 'undefined', so the check needs to be changed to
'!supportsLazyLoading' in order to work properly.
> Fix Lazy Load Image example

- src/InView.tsx
- src/__tests__/hooks.test.js
- src/useInView.tsx
This fixes #303 by clearing the `inView` status when the `ref` changes.
> Clear inView status if ref is removed

- src/InView.tsx
- src/useInView.tsx
- stories/Hooks.story.tsx
Don't reset the state if the hook or component has `triggerOnce` set.
> fix: the inView state could be reset with triggerOnce #311

- src/__tests__/hooks.test.js
- src/useInView.tsx
This is a potential fix for the infinite loop seen in #308 
Will need to try it out, to see if solves the issue
> fix: don't clear the inView state if we get a node

- src/InView.tsx
- src/__tests__/Observer.test.js
`onChange` could potentially be triggered when using the `<InView>` component, since it never removed the observer when setting `skip` later.
> fix: shouldn't trigger onchange when skipping

- src/index.tsx
This is going to cause a Rollup warning when bundling, and will therefor be removed in version 9.0.0. Closes #381 
```
Entry module "src/index.tsx" is using named and default exports together. 
Consumers of your bundle will have to use `ReactIntersectionObserver["default"]` to access the default export, which may not be what you want. Use `output.exports: "named"` to disable this warning
```
> fix: add back default export for InView

- package.json
- src/__tests__/hooks.test.tsx
- src/useInView.tsx
- yarn.lock
This fixes ensures Array thresholds are converted to a string when passed to the `useCallback` dependency array. This prevents infinite rerenders caused by arrays being recreated every render.
> fix: stringify array thresholds

- docs/Recipes.md
Description of using intersection observer for animations suggest setting `triggerOnce`, while not doing it then in code example.
> Fix: recipes animation example to trigger once

- src/test-utils.ts
Currently, the test-utils utility sets up the IntersectionObserver mock in a `beforeAll`. Some test frameworks, such as jest, have an option to reset all mocks before each test. In jest this is `resetMocks: true`. When using this config option, jest resets the IntersectionObserver mock, causing tests to break.
This PR changes the implementation to set up the mock in a `beforeEach` so that it will be set up AFTER the resetting.
The `resetMocks: true` option is now set BY DEFAULT in create-react-app v4, so I expect this will be a common issue once folks upgrade.
See: https://jestjs.io/docs/en/configuration#resetmocks-boolean
See: https://github.com/facebook/create-react-app/blob/v4.0.0/CHANGELOG.md#jest
> feat: use beforeEach instead of beforeAll

- src/observers.ts
Sometimes the `thresholds` value on the `IntersectionObserver` instance could be `undefined`. Add a fallback to a default value in the cases where the browser doesn't set it.
This fixes #414
> fix: ensure thresholds is defined

- src/__tests__/hooks.test.tsx
- src/observers.ts
This is a followup to #415, that ensures the `threshold` value defined is used, in case the Observer doesn't contain the `thresholds` value. Before it would just revert to using `threshold: 0`.
> fix: ensure threshold fallbacks to options value if undefined

- README.md
- src/__tests__/hooks.test.tsx
- src/test-utils.ts
This expands the `test-utils` to support defining a `threshold` value when checking for `isIntersecting`. Before you could only give a `boolean`.
This should allow you test more complex `threshold` based scenarios.
> feat: add support for testing threshold values

- src/observers.ts
IntersectionObserver roots were tracked in a `Map`. This ensures it's possible to reuse the Intersection Observer instance if they share the same options. Changed to use a `WeakMap`, so unused `root` elements can be garbage collected.
Closes #462
> fix: use WeakMap to avoid memory leak

- src/index.tsx
- src/observe.ts
- src/test-utils.ts
#519 and #522  had the side effect of including all the source files in the package, because the `test-utils.ts` was importing the files. The package should only include the bundle (cjs,esm,umd) files, and the `test-utils.js` file.
> fix: undo the clear observers in test-utils

- README.md
- src/InView.tsx
- src/__tests__/InView.test.tsx
- src/__tests__/hooks.test.tsx
- src/index.tsx
- src/observe.ts
- src/test-utils.ts
- src/useInView.tsx
This is solution for #495 that adds support for a `fallbackInView` value.
You can set the fallback globally:
```js
import { defaultFallbackInView } from 'react-intersection-observer';
defaultFallbackInView(true); // or 'false'
```
You can also define the fallback locally on `useInView` or `<InView>` as an
option. This will override the global fallback value.
```jsx
import React from 'react';
import { useInView } from 'react-intersection-observer';
const Component = () => {
const { ref, inView, entry } = useInView({
fallbackInView: true,
});
return (
<div ref={ref}>
<h2>{`Header inside viewport ${inView}.`}</h2>
</div>
);
};
```
> feat: add support for `fallbackInView`

- src/test-utils.ts
Hello! I've been debugging an error in my tests and keep seeing what I believe is a typo in this error message. Small thing but figured I'd put up a PR to change it!
> fix: Correct typo in test error

- README.md
- docs/Recipes.md
- src/__tests__/hooks.test.tsx
- src/index.tsx
- src/stories/Hooks.story.tsx
- src/useInView.tsx
* Add support for `onChange` in the `useInView` hook. Useful for triggering tracking events.
> feat: support onChange on useInView

- package.json
- scripts/build-copy.js
Microbundle had changed the name of the `modern` file, so it wasn't properly mapped in the `package.json`.
> fix: correct microbundle output paths

- package.json
MicroBundle expects the`default` field, and uses it to generate the correct name of the exported file. When using `import` the file wasn't generated.
> fix: use the default field

- package.json
- scripts/build-copy.js
Trying to solve the mess that is NPM packages:
* `main` still points to a CommonJS (`.js`) file.
* `modules` points to a `.esm.js` file. This seems to be what most bundles (Webpack, Vite) use.
* `exports` includes both the CommonJS (`.js`) and `.mjs` export. This is what Node will look for.
This solves #560 for now.
> fix: export module as `esm.js`

- package.json
in TS 4.7+, TypeScript introduced a node16/next module mode.
in this mode, if libraries are using "exports" field on package.json, each "exports" field needs "types" field, or fail to load typings.
for more information, see release note: https://devblogs.microsoft.com/typescript/announcing-typescript-4-7/#esm-nodejs
> fix: Add support for TS 4.7+ node16/next module

- .eslintrc.js
- .storybook/main.js
- README.md
- src/stories/Hooks.story.tsx
- src/useInView.tsx
Rewrite the internals of `useInView` to allow it to handle inline ref functions, without causing infinite loops.
* Convert the `useCallback` ref function to a `useState` that triggers a `useEffect`.
Closes #572
> feat: rewrite internals to use setState for `ref`

- src/useInView.tsx
Hello!
I got an error `ReferenceError: cannot access 'unobserve' before initialization` when IntersectionObserver is undefined, fallbackInView and triggerOnce of useInView is true.
When that condition is met, 'unobserve' is before initialization at line 73 in useInView.tsx.
So I added an initialization line and created this PR. Please check it.
> fix: cannot access 'unobserve' before initialization

- src/useInView.tsx
This is an attempt to reduce the amount of re-renders generated by the `useInView` hook. We can leverage the built-in batching during the render cycle to eliminate the need for this reset `useEffect` that should have a really nice impact on performance. https://beta.reactjs.org/learn/you-might-not-need-an-effect#adjusting-some-state-when-a-prop-changes goes over an explanation of this, I honestly wasn't aware of the pattern until I read it but it seemed pertinent for here.
I'm not too familiar with vitest and couldn't determine a great way to test the number of re-renders in the current testing setup, but thought I'd open this to get your read on it before diving any deeper.
I see this referenced in https://github.com/thebuilder/react-intersection-observer/issues/572 so not sure if this …
> fix: remove extra useEffect used for resetting initial state

- .github/workflows/release.yml
- README.md
Update the old `master` branch to modern `main`
> fix: rename master to main

- package.json
Ensure the package is published when PR's a merged to `main`
> fix: publish main with semantic releases

- README.md
- src/index.tsx
Restrict the usage of "as" to intrinsic components to avoid any issues with the ref. Add documentation to tell developers to use the hook otherwise.
> fix: restrict type on the "as" prop

- package.json
- tsup.config.ts
> fix: target es2018

- README.md
- src/test-utils.ts
Fix the typo
- Comment in test-utils.ts `Rest -> Reset`.
- README.md `wil -> will`
> Fix: typo in the comment

- src/InView.tsx
Next.js has updated or changed React, causing it to call `componentWillUnmount`, followed by `componentDidMount`. The `componentDidMount` was not included in the `<InView>` component, causing it to just unmount itself.
This is most likely caused by StrictMode, similar to how it tests `useEffect`.
https://react.dev/reference/react/Component#componentdidmount
Why it hasn't been a problem before, and only affects the Next.js app router is a great question.
Fixes #649
> fix: add componentDidMount to InView

- package.json
- pnpm-lock.yaml
- storybook/package.json
Fix the Publint warning:
* https://publint.dev/react-intersection-observer@9.5.3
* https://publint.dev/rules#export_types_invalid_format
After TypeScript 5.0, the `types` in `exports` should be an .mts file, to correctly reflect that it's exported as a module.
> fix: export .d.mts file for types

- src/test-utils.ts
Fetching `act` from `react-dom/test-utils` is deprecated, but keep support for it for now.
Fixes #674
> fix: support old act from react-dom

- README.md
> polyfill.io, a popular JavaScript library service, can no longer be trusted and should be removed from websites.
Source: [https://blog.cloudflare.com/automatically-replacing-polyfill-io-links-with-cloudflares-mirror-for-a-safer-internet](https://blog.cloudflare.com/automatically-replacing-polyfill-io-links-with-cloudflares-mirror-for-a-safer-internet)
> docs(README.md): replace the reference to `polyfill.io` with Cloudflare equivalent

- README.md
- docs/Recipes.md
- Remove native loading fallback example, and recommend not using `IntersectionObserver` for lazy loading images
- Use the markdown syntax for notes and warnings
> docs: update readme and recipes

- .github/workflows/pkg-pr.yml
- Add [pkg.pr.new](https://github.com/stackblitz-labs/pkg.pr.new) to preview packages before merging PR's.
> ci: use pkg-pr-new to publish preview packages

- package.json
Semantic release was trying to publish the `dist` directory, instead of the `root`.
Fix this configuration.
> ci: fix semantic release config

- .github/workflows/test.yml
- package.json
The command to install Playwright in the CI pipeline was incorrectly using `pnpx` instead `pnpm exec`
> Fix Playwright install script

- src/index.tsx
- Add the missing `Document` type to options
Thanks to [bizwisedan](https://github.com/bizwisedan)
> fix: align IntersectionObserver options with DOM API

- package.json
- pnpm-lock.yaml
- storybook/package.json
This pull request includes updates to dependencies and formatting changes in the `package.json` and `storybook/package.json` files. The most important changes include updating various dependencies to their latest versions for both production and development environments.
Dependency updates:
* [`package.json`](diffhunk://#diff-7ae45ad102eab3b6d7e7896acd08c427a9b25b346470d7bc6507b6481575d519L114-R127): Updated `@arethetypeswrong/cli` to `^0.17.2`, `@types/react` to `^19.0.2`, and `lint-staged` to `^15.3.0`.
* [`storybook/package.json`](diffhunk://#diff-9dff916c44fa99f82c4d398dd1c1abaf99f3598689f430e75910720e451185d4L18-R23): Updated `@storybook/manager-api` to `^8.4.7`, `framer-motion` to `^11.15.0`, `react` to `^19.0.0`, `react-dom` to `^19.0.0`, `tailwindcss` to `^3.4.17`, `@types/react` …
> chore: update dependencies

- README.md
- src/__tests__/hooks.test.tsx
- src/test-utils.ts
This PR changes to `test-utils`, to ensure mocking is configured in a reliable manner when using Jest
- Add back `beforeEach` to trigger the automatic mocking. This was removed in  #689 
- Keep the `beforeAll` hook
- Add a check to `setupIntersectionMocking` method, so it only runs if mocking hasn't been set up
- Introduce a `destroyIntersectionMocking` method to clear all mocking, and revert to the browser implementation
Closes #699
> feat: restore beforeEach in test utils

- src/__tests__/hooks.test.tsx
- src/test-utils.ts
- Always recreate the mock function in a `beforeEach`.
- Drop `beforeAll`, since it would be overwritten by the `beforeEach`
- Drop checking if the IntersectionObserver is already mocked, since it can't be reliably determined. 
Fixes #699
> fix: always recreate observer in `beforeEach`

- package.json
This pull request includes a small change to the `package.json` file. The change updates the repository URL to use the `git+https` protocol.
* [`package.json`](diffhunk://#diff-7ae45ad102eab3b6d7e7896acd08c427a9b25b346470d7bc6507b6481575d519L38-R38): Updated the repository URL from `https` to `git+https`.
> chore: update package url in package.json

- README.md
- **Before**: React implementation of the [Intersection Observer API](https://developer.mozilla.org/en-US/docs/Web/API/Intersection_Observer_API) to tell you when an element enters or leaves the viewport. Contains both a [Hooks](https://github.com/thebuilder/react-intersection-observer#useinview-hook), [render props](https://github.com/thebuilder/react-intersection-observer#render-props) and [plain children](https://github.com/thebuilder/react-intersection-observer#plain-children) implementation.
- **After**: A React implementation of the [Intersection Observer API](https://developer.mozilla.org/en-US/docs/Web/API/Intersection_Observer_API) to tell you when an element enters or leaves the viewport. Contains [Hooks](https://github.com/akshay-vs/react-intersection-observer#useinview-hook), …
> Fix minor grammatical issue in documentation intro
